[package]
name = "graphql_query_diff"
version = "0.1.0"
edition = "2021"

[dependencies]
graphql-parser = "0.4.0"
serde = {version = "1.0.214", features = ["derive"]}
serde_json = "1.0"
console = "0.15.8"
termcolor = "1.4.1"
